FactoryGirl.define do
  factory :user do
    # Each email and account name generated by FactoryGirl are guarnteed to be
    # unique with these sequence blocks
    sequence :email do |i|
      "User#{i}@test.com"
    end
    sequence :account_name do |i|
      "account#{i}"
    end
    password 'password'
    password_confirmation 'password'

    trait :with_character do
      after(:build) do |user|
        user.character ||= FactoryGirl.build(:character, :user => user)
      end
    end

    trait :with_post do
      after(:create) do |instance|
        instance.posts << FactoryGirl.create(:post)
      end
    end
  end
end
